
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding-byredhat
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: argocd-role-byredhat
subjects:
- kind: ServiceAccount
  name: argocd-sample-application-controller
  namespace: argocd
