
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role-byredhat
  namespace: argocd
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - Get
  - List
  - Watch
  - Patch
