# Require update with the newly created bucket values, see ../tempo-bucket-claim.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.secretName }}
  namespace: {{ .Values.namespace }}
stringData:
  bucket: {{ .Values.storage.bucket }}
  endpoint: {{ .Values.storage.endpoint }}
  access_key_id: {{ .Values.storage.accessKeyId }}
  access_key_secret: {{ .Values.storage.accessKeySecret }}
type: Opaque