apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-knbaremetal
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://api.knbaremetal.kuwaitnet.lab:6443'
  project: default
  source:
    helm:
      valueFiles:
        - values-knbaremetal.yaml
    path: tempo
    repoURL: 'https://github.com/yahyakangsawala/argocd-demo.git'
    targetRevision: master
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #   retry:
  #     backoff:
  #       duration: 5s
  #       factor: 2
  #       maxDuration: 20m
  #     limit: 5
