apiVersion: v2
name: istio-resources
description: istio resources like Gateway, VirtualService, etc...
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Sarafou Balde
    email: sbalde@redhat.com
    url: https://www.redhat.com