apiVersion: v2
name: observability-plugin
description: A simple Helm chart for observability console plugin custom resource
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Sarafou Balde
    email: sbalde@redhat.com
    url: https://www.redhat.com