apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateways-nppayhub
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
  - list:
      elements:
      - cluster: nppayhub
        url: https://api.nppayhub.corp.bbynuat.com:6443
        values:
          name: ingressgateway-nppayhub
          chartPath: gateway
          valuesFile: values-ingress-nppayhub.yaml
#      - cluster: bbynnpocp
#        url: https://api.bbynnpocp.corp.bbynuat.com:6443
#        values:
#          name: egressgateway-bbynnpocp
#          chartPath: gateway
#          valuesFile: values-egress-bbynnpocp.yaml          
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        gitops: operator
    spec:
      project: default
      ignoreDifferences:
        - group: ""
          kind: ServiceAccount
          jsonPointers:
            - /imagePullSecrets
      # syncPolicy:
      #   automated:
      #     prune: false
      #     selfHeal: true
      #   retry:
      #     limit: 5
      #     backoff:
      #       duration: 5s
      #       factor: 2
      #       maxDuration: 20m
      source:
        repoURL: https://swan02.corp.boubyan.com:7991/scm/opt/np-servicemesh.git
        targetRevision: master
        path: '{{values.chartPath}}'
        helm:
          valueFiles:
            - '{{ values.valuesFile }}'
      destination:
        server: https://api.nppayhub.corp.bbynuat.com:6443
        namespace: istio-system
