apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-app-of-apps-nppayhub
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/nppayhub
    repoURL: https://swan02.corp.boubyan.com:7991/scm/opt/np-servicemesh.git
    targetRevision: master
  #syncPolicy:
  #  automated:
  #    prune: false
  #    selfHeal: true