{{- if eq .Values.gateway.type "ingress"  -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews-canary-virtual-service
  namespace: {{ .Values.service.namespace }}
spec:
  hosts:
  - reviews
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
        port:
          number: 9080
      weight: 33
    - destination:
        host: reviews
        subset: v2
        port:
          number: 9080
      weight: 33
    - destination:
        host: reviews
        subset: v3
        port:
          number: 9080
      weight: 34
{{- end }} 
         